=== aarizaq/Denacast/src/common/cbr/areas.dtd
<!ELEMENT arealist (area)+>

<!ATTLIST arealist
    dimensions CDATA #REQUIRED>

<!ELEMENT area (min+,max+,prefix)>
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>
<!ELEMENT prefix (#PCDATA)>

<!ATTLIST min dimension CDATA #REQUIRED>
<!ATTLIST max dimension CDATA #REQUIRED>

=== aarizaq/Denacast/src/common/cbr/areas_nodes_2d_15000.xml
<!DOCTYPE arealist SYSTEM "areas.dtd">
<arealist dimensions="2">
	<area>
		<min dimension="0">-1000</min>
		<min dimension="1">-1000</min>
		<max dimension="0">-74.19985</max>
		<max dimension="1">-118.9955</max>
		<prefix>00000000</prefix>
	</area>
	<area>
		<min dimension="0">-1000</min>
		<min dimension="1">-118.9955</min>
		<max dimension="0">-74.19985</max>
		<max dimension="1">-85.57875</max>
		<prefix>00000001</prefix>
	</area>
	<area>
		<min dimension="0">-74.19985</min>
		<min dimension="1">-1000</min>
		<max dimension="0">-51.60495</max>
		<max dimension="1">-93.45035</max>
		<prefix>00000010</prefix>
	</area>
	<area>
		<min dimension="0">-74.19985</min>
		<min dimension="1">-93.45035</min>
		<max dimension="0">-51.60495</max>
		<max dimension="1">-85.57875</max>
		<prefix>00000011</prefix>
	</area>
	<area>
		<min dimension="0">-1000</min>
		<min dimension="1">-85.57875</min>
		<max dimension="0">-56.3975</max>
		<max dimension="1">-80.7264</max>
		<prefix>00000100</prefix>
	</area>
	<area>
		<min dimension="0">-1000</min>
		<min dimension="1">-80.7264</min>
		<max dimension="0">-56.3975</max>
		<max dimension="1">-72.4187</max>
		<prefix>00000101</prefix>
	</area>
	<area>
		<min dimension="0">-56.3975</min>
		<min dimension="1">-85.57875</min>
		<max dimension="0">-51.60495</max>
		<max dimension="1">-78.61505</max>
		<prefix>00000110</prefix>
	</area>
	<area>
		<min dimension="0">-56.3975</min>
		<min dimension="1">-78.61505</min>
		<max dimension="0">-51.60495</max>
		<max dimension="1">-72.4187</max>
		<prefix>00000111</prefix>
	</area>
	<area>
		<min dimension="0">-51.60495</min>
		<min dimension="1">-1000</min>
		<max dimension="0">-42.3958</max>
		<max dimension="1">-83.2466</max>
		<prefix>00001000</prefix>
	</area>
	<area>
		<min dimension="0">-51.60495</min>
		<min dimension="1">-83.2466</min>
		<max dimension="0">-42.3958</max>
		<max dimension="1">-77.3301</max>
		<prefix>00001001</prefix>
	</area>
	<area>
		<min dimension="0">-42.3958</min>
		<min dimension="1">-1000</min>
		<max dimension="0">-34.9886</max>
		<max dimension="1">-81.857</max>
		<prefix>00001010</prefix>
	</area>
	<area>
		<min dimension="0">-42.3958</min>
		<min dimension="1">-81.857</min>
		<max dimension="0">-34.9886</max>
		<max dimension="1">-77.3301</max>
		<prefix>00001011</prefix>
	</area>
	<area>
		<min dimension="0">-51.60495</min>
		<min dimension="1">-77.3301</min>
		<max dimension="0">-46.89775</max>
		<max dimension="1">-74.75235</max>
		<prefix>00001100</prefix>
	</area>
	<area>
		<min dimension="0">-51.60495</min>
		<min dimension="1">-74.75235</min>
		<max dimension="0">-46.89775</max>
		<max dimension="1">-72.4187</max>
		<prefix>00001101</prefix>
	</area>
	<area>
		<min dimension="0">-46.89775</min>
		<min dimension="1">-77.3301</min>
		<max dimension="0">-34.9886</max>
		<max dimension="1">-74.925</max>
		<prefix>00001110</prefix>
	</area>
	<area>
		<min dimension="0">-46.89775</min>
		<min dimension="1">-74.925</min>
		<max dimension="0">-34.9886</max>
		<max dimension="1">-72.4187</max>
		<prefix>00001111</prefix>
	</area>
	<area>
		<min dimension="0">-1000</min>
		<min dimension="1">-72.4187</min>
		<max dimension="0">-49.06175</max>
		<max dimension="1">-70.17675</max>
		<prefix>00010000</prefix>
	</area>
	<area>
		<min dimension="0">-1000</min>
		<min dimension="1">-70.17675</min>
		<max dimension="0">-49.06175</max>
		<max dimension="1">-66.02675</max>
		<prefix>00010001</prefix>
	</area>
	<area>
		<min dimension="0">-49.06175</min>
		<min dimension="1">-72.4187</min>
		<max dimension="0">-44.3959</max>
		<max dimension="1">-70.363</max>
		<prefix>00010010</prefix>
	</area>
	<area>
		<min dimension="0">-49.06175</min>
		<min dimension="1">-70.363</min>
		<max dimension="0">-44.3959</max>
		<max dimension="1">-66.02675</max>
		<prefix>00010011</prefix>
	</area>
	<area>
		<min dimension="0">-1000</min>
		<min dimension="1">-66.02675</min>
		<max dimension="0">-54.2664</max>
		<max dimension="1">-48.0319</max>
		<prefix>00010100</prefix>
	</area>
	<area>
		<min dimension="0">-1000</min>
		<min dimension="1">-48.0319</min>
		<max dimension="0">-54.2664</max>
		<max dimension="1">-17.5015</max>
		<prefix>00010101</prefix>
	</area>
	<area>
		<min dimension="0">-54.2664</min>
		<min dimension="1">-66.02675</min>
		<max dimension="0">-44.3959</max>
		<max dimension="1">-30.02505</max>
		<prefix>00010110</prefix>
	</area>
	<area>
		<min dimension="0">-54.2664</min>
		<min dimension="1">-30.02505</min>
		<max dimension="0">-44.3959</max>
		<max dimension="1">-17.5015</max>
		<prefix>00010111</prefix>
	</area>
	<area>
		<min dimension="0">-44.3959</min>
		<min dimension="1">-72.4187</min>
		<max dimension="0">-40.90355</max>
		<max dimension="1">-68.22845</max>
		<prefix>00011000</prefix>
	</area>
	<area>
		<min dimension="0">-44.3959</min>
		<min dimension="1">-68.22845</min>
		<max dimension="0">-40.90355</max>
		<max dimension="1">-64.45215</max>
		<prefix>00011001</prefix>
	</area>
	<area>
		<min dimension="0">-40.90355</min>
		<min dimension="1">-72.4187</min>
		<max dimension="0">-34.9886</max>
		<max dimension="1">-67.1221</max>
		<prefix>00011010</prefix>
	</area>
	<area>
		<min dimension="0">-40.90355</min>
		<min dimension="1">-67.1221</min>
		<max dimension="0">-34.9886</max>
		<max dimension="1">-64.45215</max>
		<prefix>00011011</prefix>
	</area>
	<area>
		<min dimension="0">-44.3959</min>
		<min dimension="1">-64.45215</min>
		<max dimension="0">-38.09465</max>
		<max dimension="1">-26.2013</max>
		<prefix>00011100</prefix>
	</area>
	<area>
		<min dimension="0">-44.3959</min>
		<min dimension="1">-26.2013</min>
		<max dimension="0">-38.09465</max>
		<max dimension="1">-17.5015</max>
		<prefix>00011101</prefix>
	</area>
	<area>
		<min dimension="0">-38.09465</min>
		<min dimension="1">-64.45215</min>
		<max dimension="0">-34.9886</max>
		<max dimension="1">-58.8092</max>
		<prefix>00011110</prefix>
	</area>
	<area>
		<min dimension="0">-38.09465</min>
		<min dimension="1">-58.8092</min>
		<max dimension="0">-34.9886</max>
		<max dimension="1">-17.5015</max>
		<prefix>00011111</prefix>
	</area>
	<area>
		<min dimension="0">-34.9886</min>
		<min dimension="1">-1000</min>
		<max dimension="0">-31.6209</max>
		<max dimension="1">-71.8295</max>
		<prefix>00100000</prefix>
	</area>
	<area>
		<min dimension="0">-34.9886</min>
		<min dimension="1">-71.8295</min>
		<max dimension="0">-31.6209</max>
		<max dimension="1">-63.6851</max>
		<prefix>00100001</prefix>
	</area>
	<area>
		<min dimension="0">-31.6209</min>
		<min dimension="1">-1000</min>
		<max dimension="0">-29.4008</max>
		<max dimension="1">-70.89755</max>
		<prefix>00100010</prefix>
	</area>
	<area>
		<min dimension="0">-31.6209</min>
		<min dimension="1">-70.89755</min>
		<max dimension="0">-29.4008</max>
		<max dimension="1">-63.6851</max>
		<prefix>00100011</prefix>
	</area>
	<area>
		<min dimension="0">-34.9886</min>
		<min dimension="1">-63.6851</min>
		<max dimension="0">-33.8707</max>
		<max dimension="1">-62.39185</max>
		<prefix>00100100</prefix>
	</area>
	<area>
		<min dimension="0">-34.9886</min>
		<min dimension="1">-62.39185</min>
		<max dimension="0">-33.8707</max>
		<max dimension="1">-61.51685</max>
		<prefix>00100101</prefix>
	</area>
	<area>
		<min dimension="0">-33.8707</min>
		<min dimension="1">-63.6851</min>
		<max dimension="0">-29.4008</max>
		<max dimension="1">-62.0562</max>
		<prefix>00100110</prefix>
	</area>
	<area>
		<min dimension="0">-33.8707</min>
		<min dimension="1">-62.0562</min>
		<max dimension="0">-29.4008</max>
		<max dimension="1">-61.51685</max>
		<prefix>00100111</prefix>
	</area>
	<area>
		<min dimension="0">-29.4008</min>
		<min dimension="1">-1000</min>
		<max dimension="0">-26.47485</max>
		<max dimension="1">-72.3848</max>
		<prefix>00101000</prefix>
	</area>
	<area>
		<min dimension="0">-29.4008</min>
		<min dimension="1">-72.3848</min>
		<max dimension="0">-26.47485</max>
		<max dimension="1">-65.06145</max>
		<prefix>00101001</prefix>
	</area>
	<area>
		<min dimension="0">-26.47485</min>
		<min dimension="1">-1000</min>
		<max dimension="0">-21.19115</max>
		<max dimension="1">-76.6196</max>
		<prefix>00101010</prefix>
	</area>
	<area>
		<min dimension="0">-26.47485</min>
		<min dimension="1">-76.6196</min>
		<max dimension="0">-21.19115</max>
		<max dimension="1">-65.06145</max>
		<prefix>00101011</prefix>
	</area>
	<area>
		<min dimension="0">-29.4008</min>
		<min dimension="1">-65.06145</min>
		<max dimension="0">-24.56165</max>
		<max dimension="1">-62.64065</max>
		<prefix>00101100</prefix>
	</area>
	<area>
		<min dimension="0">-29.4008</min>
		<min dimension="1">-62.64065</min>
		<max dimension="0">-24.56165</max>
		<max dimension="1">-61.51685</max>
		<prefix>00101101</prefix>
	</area>
	<area>
		<min dimension="0">-24.56165</min>
		<min dimension="1">-65.06145</min>
		<max dimension="0">-21.19115</max>
		<max dimension="1">-63.92215</max>
		<prefix>00101110</prefix>
	</area>
	<area>
		<min dimension="0">-24.56165</min>
		<min dimension="1">-63.92215</min>
		<max dimension="0">-21.19115</max>
		<max dimension="1">-61.51685</max>
		<prefix>00101111</prefix>
	</area>
	<area>
		<min dimension="0">-34.9886</min>
		<min dimension="1">-61.51685</min>
		<max dimension="0">-29.5136</max>
		<max dimension="1">-60.09645</max>
		<prefix>00110000</prefix>
	</area>
	<area>
		<min dimension="0">-34.9886</min>
		<min dimension="1">-60.09645</min>
		<max dimension="0">-29.5136</max>
		<max dimension="1">-59.2169</max>
		<prefix>00110001</prefix>
	</area>
	<area>
		<min dimension="0">-29.5136</min>
		<min dimension="1">-61.51685</min>
		<max dimension="0">-26.03335</max>
		<max dimension="1">-60.49075</max>
		<prefix>00110010</prefix>
	</area>
	<area>
		<min dimension="0">-29.5136</min>
		<min dimension="1">-60.49075</min>
		<max dimension="0">-26.03335</max>
		<max dimension="1">-59.2169</max>
		<prefix>00110011</prefix>
	</area>
	<area>
		<min dimension="0">-34.9886</min>
